# Generated by Django 3.0.4 on 2020-04-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7),
        ),
    ]
