# Generated by Django 3.0.4 on 2020-04-20 04:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_blogpost_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Item',
        ),
    ]
