# Generated by Django 3.0.4 on 2020-04-20 04:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_auto_20200420_0410'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='BlogPost',
        ),
    ]
