# Generated by Django 3.0.4 on 2020-04-20 16:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_blogpost_inventory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='ItemPost',
        ),
    ]
